name: OpenLogin - Passwordless Login

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

env:
  NODE_VERSION: 14

jobs:
  run-tests:
    name: Run OpenLogin - Passwordless Login tests
    strategy:
      matrix:
        include:
          - browser: firefox
            os: macos-latest
    runs-on: ${{ matrix.os }}
    outputs:
      conclusion: ${{ steps.run-tests.conclusion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: setup-node
        name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
        continue-on-error: true

      - id: yarn-install
        name: Install Node.js dependencies
        if: steps.setup-node.outcome == 'success'
        run: yarn install --frozen-lockfile
        continue-on-error: true

      - id: yarn-install-deps
        name: Install Ubuntu dependencies
        if: steps.yarn-install.outcome == 'success' && startsWith(matrix.os, 'ubuntu')
        run: yarn run playwright install-deps ${{ matrix.browser }}
        continue-on-error: true

      - id: configure-aws
        name: Configure AWS credentials
        if: steps.yarn-install.outcome == 'success' && steps.yarn-install-deps.outcome != 'failure'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        continue-on-error: true

      - id: download-state
        name: Download remote browser snapshots
        if: steps.configure-aws.outcome == 'success'
        run: aws s3 cp s3://torus-e2e-tests/openlogin/login-with-passwordless/ openlogin/login-with-passwordless/ --recursive
        continue-on-error: true

      # TODO: Uncomment this to run tests
      # - id: run-tests
      #   name: Run tests
      #   if: steps.download-state.outcome == 'success
      #   run: yarn run playwright test --config openlogin/login-with-passwordless/index.config.ts --project ${{ matrix.browser }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-on-${{ matrix.browser }}-${{ matrix.os }}
          path: test-results/
          if-no-files-found: ignore

  update-status:
    name: Update OpenLogin - Passwordless Login status
    needs: run-tests
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - name: Update status
        uses: fjogeleit/http-request-action@master
        with:
          url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.PASSWORDLESS_COMPONENT_ID }}
          customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
          method: PATCH
          contentType: 'application/json'
          timeout: 10000
          data: >-
            { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
