name: Wallet - SDK

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

env:
  NODE_VERSION: 16
  FORCE_COLOR: 3

jobs:
  run-tests:
    name: Run Wallet - SDK tests
    strategy:
      matrix:
        env: [prod]
        browser: [firefox, chromium]
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            browser: chromium
            env: cyan
          - os: macos-latest
            browser: webkit
            env: beta
          - os: macos-latest
            browser: webkit
            env: prod

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get Yarn cache directory
        id: get-yarn-cache-dir
        run: echo "::set-output name=path::$(yarn cache dir)"

      - name: Cache Yarn dependencies
        uses: actions/cache@v3.0.1
        with:
          path: ${{ steps.get-yarn-cache-dir.outputs.path }}
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Install Ubuntu dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: yarn run playwright install-deps ${{ matrix.browser }}

      - name: Run tests
        run: yarn run playwright test --config wallet/sdk/index.config.ts --project ${{ matrix.browser }}

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results-on-${{ matrix.browser }}-${{ matrix.os }}
          path: test-results/
          if-no-files-found: ignore
